sudo: required

services:
  - docker

script:
  - 'make build-nc'
  - 'make test-config'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make publish ;
    fi

notifications:
  email: false