version: '3'

services:

# https://github.com/KungAlex/rest-mqtt-proxy
  rest-mqtt-proxy:
    image: kungalex/rest-mqtt-proxy:latest
    #container_name: rest-mqtt-proxy
    # restart: always
    environment:
      - APP_CONFIG_FILE=/srv/rest-mqtt-proxy/config.ini
      - PRE_MAPPING_DIR=/srv/rest-mqtt-proxy/mappings

    volumes:
      - ${PWD}/config/dev/config-dc.ini:/srv/rest-mqtt-proxy/config.ini:ro
      - ${PWD}/config/dev/mappings/:/srv/rest-mqtt-proxy/mappings/:ro

    ports:
     - "5000:5000"



# https://hub.docker.com/_/eclipse-mosquitto/
  mosquitto:
    image: eclipse-mosquitto
    #container_name: moquitto
    # restart: always
    ports:
     - "9001:9001"
     - "1883:1883"

    #1883 MQTT port
    #9001 Websocket port

# https://hub.docker.com/_/influxdb/
  influxdb:
    image: influxdb
    #container_name: influxdb
    # restart: always
    environment:
     - INFLUXDB_USER="admin"
     - INFLUXDB_USER_PASSWORD="admin
     - INFLUXDB_DB="iot"
    ports:
     - "8083:8083"
     - "8086:8086"

    #8086 HTTP API port
    #8083 Administrator interface port, if it is enabled
    #2003 Graphite support, if it is enabled

# https://hub.docker.com/_/chronograf/
  chronograf:
    image: chronograf
    #container_name: chronograf
    #restart: always
    links:
      - influxdb
    ports:
      - 8888:8888

    #8888 HTTP Frontend

