kind: MQTTSubscriptionV1
subregex: "test-a/topic/#"
description: 'Test Topics'
event_handlers:
  default_manager: default_output_handler
  persistent_manager: push_influxdb_handler

---

kind: MQTTSubscriptionV1
subregex: "test-b/topic/#"
description: 'Test Topics'
event_handlers:
  default_manager: default_output_handler
  persistent_manager: push_influxdb_handler
